bridge("Jump bridge", "jump", "jump.png", "A method where you are run jumping wal bridging.")
bridge("MJ bridge", "mj", "mj.png", "A way to start jump by placing a block and looking at your feet.")
bridge("Icy bridge", "icy", "icy.png", "Moving diagonaly wal placing A block on each turn.")
bridge("Double bridge", "doubleBridge", "doubleBridge.png", "Moving forwards wal flicking to the side to place blocks there to.")
bridge("Triple bridge", "tripleBridge", "tripleBridge.png", "Click bridging moving in a sanking pattern to make a 3 think bridge.")
bridge("Triple Spam", "triSpam", "trispam.png", "Moving forwards wal flicking from side to side, place blocks there to.")
bridge("Up bridge", "up", "up.png", "By placing a block and and jumping you can ''jump bridge'' up.")
bridge("Double Icy", "douicy", "douicy.png", "Double bridge but your moving diagonally.")
bridge("Down bridge", "down", "down.png", "Place and block and fall down wal looking at it, starts a bridge.")